title: i cant beleave you done this.
theme: minima
author: Rayden
email: paragkapoor20@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,
  molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum
  numquam blanditiis harum quisquam eius sed odit fugiat iusto .

# social links
twitter_username: Rayden_284 # DO NOT include the @ character, or else the build will fail!
github_username:  Rayden482 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
